import dotenv from 'dotenv';
dotenv.config();

// Validate required environment variables
const requiredEnvVars = ['OPENEMR_BASE_URL', 'OPENEMR_CLIENT_ID', 'OPENEMR_CLIENT_SECRET', 'OPENEMR_REDIRECT_URI'];
for (const envVar of requiredEnvVars) {
  if (!process.env[envVar]) {
    throw new Error(`Missing required environment variable: ${envVar}. See .env.example for reference.`);
  }
}

const BASE_URL = process.env.OPENEMR_BASE_URL;

export const OPENEMR_CONFIG = {
  BASE_URL,
  CLIENT_ID: process.env.OPENEMR_CLIENT_ID,
  CLIENT_SECRET: process.env.OPENEMR_CLIENT_SECRET,
  REDIRECT_URI: process.env.OPENEMR_REDIRECT_URI,
  API_PREFIX: process.env.OPENEMR_API_PREFIX || "/apis/default/api",
  
  // OAuth endpoints
  AUTH_URL: `${BASE_URL}/oauth2/default/authorize`,
  TOKEN_URL: `${BASE_URL}/oauth2/default/token`,
  JWKS_URL: `${BASE_URL}/oauth2/default/.well-known/jwks.json`,
  
  // JWT settings
  JWT_ALGORITHMS: (process.env.JWT_ALGORITHMS || 'RS256').split(','),
  JWT_ISSUER: `${BASE_URL}/oauth2/default`,
  JWT_AUDIENCE: process.env.OPENEMR_CLIENT_ID,
  
  // Token refresh settings
  // Time before expiry to trigger automatic refresh (in milliseconds)
  // Default: 5 minutes (300000ms)
  TOKEN_REFRESH_THRESHOLD: parseInt(process.env.TOKEN_REFRESH_THRESHOLD || '300000', 10),
  
  // Alternative thresholds (can be used based on preference)
  // 1 minute: 60000
  // 2 minutes: 120000
  // 5 minutes: 300000 (default)
  // 10 minutes: 600000
};

export const ALL_SCOPES = [
  "openid",
  "offline_access",
  "launch/patient",
  "api:fhir",
  "patient/AllergyIntolerance.rs",
  "patient/Appointment.rs",
  "patient/Binary.rs",
  "patient/CarePlan.rs",
  "patient/CareTeam.rs",
  "patient/Condition.rs",
  "patient/Coverage.rs",
  "patient/Device.rs",
  "patient/DiagnosticReport.rs",
  "patient/DocumentReference.rs",
  "patient/DocumentReference.$docref",
  "patient/Encounter.rs",
  "patient/Goal.rs",
  "patient/Immunization.rs",
  "patient/Location.rs",
  "patient/Media.rs",
  "patient/Medication.rs",
  "patient/MedicationRequest.rs",
  "patient/MedicationDispense.rs",
  "patient/Observation.rs",
  "patient/Organization.rs",
  "patient/Patient.rs",
  "patient/Person.rs",
  "patient/Practitioner.rs",
  "patient/Procedure.rs",
  "patient/Provenance.rs",
  "patient/QuestionnaireResponse.rs",
  "patient/RelatedPerson.rs",
  "patient/ServiceRequest.rs",
  "patient/Specimen.rs",
  "system/AllergyIntolerance.rs",
  "system/Binary.rs",
  "system/CarePlan.rs",
  "system/CareTeam.rs",
  "system/Condition.rs",
  "system/Coverage.rs",
  "system/Device.rs",
  "system/DiagnosticReport.rs",
  "system/DocumentReference.rs",
  "system/DocumentReference.$docref",
  "system/Encounter.rs",
  "system/Goal.rs",
  "system/Group.rs",
  "system/Immunization.rs",
  "system/Location.rs",
  "system/Media.rs",
  "system/Medication.rs",
  "system/MedicationRequest.rs",
  "system/MedicationDispense.rs",
  "system/Observation.rs",
  "system/Organization.rs",
  "system/Patient.rs",
  "system/Person.rs",
  "system/Practitioner.rs",
  "system/PractitionerRole.rs",
  "system/Procedure.rs",
  "system/Provenance.rs",
  "system/ValueSet.rs",
  "system/Questionnaire.rs",
  "system/QuestionnaireResponse.rs",
  "system/RelatedPerson.rs",
  "system/ServiceRequest.rs",
  "system/Specimen.rs",
  "user/AllergyIntolerance.rs",
  "user/Binary.rs",
  "user/CarePlan.rs",
  "user/CareTeam.rs",
  "user/Condition.rs",
  "user/Coverage.rs",
  "user/Device.rs",
  "user/DiagnosticReport.rs",
  "user/DocumentReference.rs",
  "user/DocumentReference.$docref",
  "user/Encounter.rs",
  "user/Goal.rs",
  "user/Immunization.rs",
  "user/Location.rs",
  "user/Media.rs",
  "user/Medication.rs",
  "user/MedicationRequest.rs",
  "user/MedicationDispense.rs",
  "user/Observation.rs",
  "user/Organization.rs",
  "user/Patient.rs",
  "user/Person.rs",
  "user/Practitioner.rs",
  "user/PractitionerRole.rs",
  "user/Procedure.rs",
  "user/Provenance.rs",
  "user/ValueSet.rs",
  "user/Questionnaire.rs",
  "user/QuestionnaireResponse.rs",
  "user/RelatedPerson.rs",
  "user/ServiceRequest.rs",
  "user/Specimen.rs",
  "api:oemr",
  "user/allergy.cruds",
  "user/appointment.cruds",
  "user/dental_issue.cruds",
  "user/document.crs",
  "user/drug.rs",
  "user/employer.s",
  "user/encounter.crus",
  "user/facility.crus",
  "user/immunization.rs",
  "user/insurance.crus",
  "user/insurance_company.crus",
  "user/insurance_type.s",
  "user/list.r",
  "user/medical_problem.cruds",
  "user/medication.cruds",
  "user/message.cud",
  "user/patient.crus",
  "user/practitioner.crus",
  "user/prescription.rs",
  "user/procedure.rs",
  "user/product.s",
  "user/soap_note.crus",
  "user/surgery.cruds",
  "user/transaction.cuds",
  "user/user.rs",
  "user/version.s",
  "user/vital.crus",
  "api:port",
  "patient/encounter.read",
  "patient/patient.read",
  "patient/appointment.read"
].join("%20");